# Generated by Django 3.0 on 2020-05-20 13:54

from django.db import migrations, models
import simulation.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='cover',
            field=models.ImageField(upload_to=simulation.models.get_file_path),
        ),
    ]
